language: node_js
branches:
  only:
  - master
  - /^deploy-.*$/

cache:
  yarn: true
  directories:
  - node_modules

notifications:
  email: false

node_js:
  - node

stages:
  - lint
  - test
  - build
jobs:
  include:
  - stage: lint
    script:
    # Run linter
    - npm run lint
  - stage: test
    script:
    # Run tests
    - npm run test
  - stage: build
    script:
    - npm run build

